<?php 

// Changes to Metatag module, fields are made required and others completely removed
include_once 'misc_modifications.metatag_alter.inc';

// Changes to Wysiwyg editor (TinyMCE), hides help texts using restrictions on defined fields
include_once 'misc_modifications.wysiwyg_alter.inc';

// Changes to workbench landingpage - My profile. Adds classes, views and menu items
include_once 'misc_modifications.workbench_alter.inc';

// Changes to page node form.
include_once 'misc_modifications.node_add_form_alter.inc';

// Changes to view of nodes.
include_once 'misc_modifications.node_view_alter.inc';

// Fix to redirect modulet - removes bug with Infinite Loops.
include_once 'misc_modifications.redirect_fix.inc';

// Custom blocks - user menu block.
include_once 'misc_modifications.blocks.inc';

// Changes to header of view "agenda_overview" with display "embedded_page".
include_once 'misc_modifications.views.inc';

// eof
