<?php
	
// Functions for tracking the file usage of [[inline tags]].
require_once dirname(__FILE__) . '/includes/media_browser_ux.file_usage.inc';

/**
 * Implements hook_init().
 */
function media_browser_ux_init() {
	drupal_add_library('media_browser_ux', 'media_browser_ux');
}
	
/**
 * Implements hook_library().
 */
function media_browser_ux_library() {
  $path = drupal_get_path('module', 'media_browser_ux');
  $libraries['media_browser_ux'] = array(
    'title' => 'Media Browser UX',
    'version' => '1',
    'js' => array(
      $path . '/js/media_browser_ux.js' => array(),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_form_alter().
 */
function media_browser_ux_form_alter(&$form, &$form_state) {
	
	// Delete one file	
	if($form['#form_id'] == 'file_entity_delete_form') {
		
		$file = file_load(arg(1));
		
		// Prevent file deletion if file is in use
	  if ($references = file_usage_list($file)) {
		  drupal_set_message(t("This file is used somewhere on the website and cannot be deleted"), "error");
		  
			unset($form['actions']['submit']);
						
			$description = "<p>".t('Before you can delete this file you must remove any references made to the file.')." ";
			$description .= "".t('For more info check the file usage overview <a href="@file-usage">here</a>', array('@file-usage' => url("file/".arg(1)."/usage"))).".</p>";
			
			$form["description"] = array(
				"#markup" => $description
			);
		}
	}
	
	// Delete multiple files
	else if($form['#form_id'] == 'file_entity_multiple_delete_confirm') {
		
		$in_use = FALSE;
				
		foreach($form['files'] as $fid => $file) {
			if(is_integer($fid)) {
				$file = file_load($fid);
				if ($references = file_usage_list($file)) {
					$in_use = TRUE;
					$form['files'][$fid]['#prefix'] = '<li class="error" style="font-weight: bold;">'; 
				}
			}
		}
		
		if($in_use) {
			unset($form['actions']['submit']);
	
			drupal_set_message(t("One or more of these files are used somewhere on the website and cannot be deleted"), "error");
			
			$description = t('Before you can delete these files you must remove any references made to the files.');
			
			$form["description"] = array(
				"#markup" => $description
			);
		}
		
	}
}

/**
 * Implements hook_menu_alter().
 */
function media_browser_ux_menu_alter(&$items) {
	
	// Disable the default file lists / views
  $items['admin/content/file']['access callback'] = FALSE;
  $items['admin/content/file/thumbnails']['access callback'] = FALSE;
}

function media_browser_ux_menu_local_tasks_alter(&$data, $router_item, $root_path) {
	if($root_path=="admin/content/file") {
		
		foreach($data['actions']['output'] as $key => $action) {
			switch($action['#link']['path']) {
				case "file/add": 
					$data['actions']['output'][$key]['#weight'] = 0;
					$data['actions']['output'][$key]['#link']['title'] = "+ Upload filer";
					$data['actions']['output'][$key]['#link']['localized_options']['attributes']['class'] = "upload-button";
				break;
				case "admin/content/file/import":
					$data['actions']['output'][$key]['#weight'] = 1;
				break;
			}
		}
	}
}