<?php
/**
 * @file
 * Drupal needs this blank file.
 */

 /**
  * Implements hook_entity_info_alter().
  */
 function rebild_base_fields_entity_info_alter(&$entity_info) {
   $entity_info['paragraphs_item']['view modes']['two_cols'] = array(
     'label' => t('Two columns'),
     'custom settings' => TRUE,
   );
   $entity_info['paragraphs_item']['view modes']['three_cols'] = array(
     'label' => t('Three columns'),
     'custom settings' => TRUE,
   );
 }
