<?php
/**
 * @file
 * Code for the Meddelelser feature.
 */

include_once 'rebild_announcement.features.inc';


/**
 * Implements hook_block_info().
 */
function rebild_announcement_block_info() {
  $blocks = array();
  $blocks['din_kommune_informerer'] = array(
    'info' => 'Din kommune informerer - forside',
    'title' => '<none>',
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function rebild_announcement_block_view($delta='') {
  $block = array();
 
  switch($delta) {
    case 'din_kommune_informerer' :
      $block['content'] = rebild_announcement_front_block_view();
    break;
  }
  return $block;
}

/**
 * Implements hook_block_configure().
 */
function rebild_announcement_block_configure($delta='') {
  $form = array();
 
  switch($delta) {
    case 'din_kommune_informerer' : 
      $form['body'] = array(
        '#type' => 'text_format',
        '#title' => t('Body'),
        '#default_value' => variable_get('announcement_front_body', ''),
      );
		break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function rebild_announcement_block_save($delta = '', $edit = array()) {
  switch($delta) {
    case 'din_kommune_informerer' :
      variable_set('announcement_front_body', $edit['body']['value']);
    break;
	}
}

/**
 * Service Colors - block view
 */
function rebild_announcement_front_block_view() {
  
	$output = "<a href='/din-kommune-informerer?dato=".date("Y")."-W".date("W", strtotime("+2 days 12 hours"))."'>";
	$output .= "<div class='announcement-front'>";
	$output .= "<div class='week-number'><span class='icon-mega-phone'></span><span>Uge ".date("W", strtotime("+2 days 12 hours"))."</span></div>";
	$output .= "<div class='body'>".variable_get('announcement_front_body', '')."</div>";
	$output .= "</div></a>";
		
	return $output;
}